server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: framework

spring:
  profiles:
    active: prod
  application:
    name: travelandrepeat-be
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_QUOTATION_FROM}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}
          connectiontimeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

# Agent Mail
mail:
  agent-to: ${MAIL_AGENT_TO}
  quotation-from: ${MAIL_QUOTATION_FROM}

cors:
  allowed-origins:
    - https://travelandrepeat.com.mx
    - https://www.travelandrepeat.com.mx
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: "*"
  allow-credentials: false

google:
  recaptcha:
    secret: ${RECAPTCHA_SECRET}
    verify-url: https://www.google.com/recaptcha/api/siteverify

banxico:
  api-url: "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos/oportuno?token="
  token: ${BANXICO_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  expiration: "3600000" # 1 hour in milliseconds

# expose health and info endpoints over HTTP
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: never

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF

