spring:
  application:
    profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: "travelandrepeatdev@gmail.com"
    password: "kxwy dfrj drej kiuj" # set secret in real app with double quotes if special chars
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
#  datasource:
#    url: jdbc
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""

# Agent Mail
mail:
  agent-to: "sereal_666@hotmail.com"
  quotation-from: "travelandrepeatdev@gmail.com"

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: "*"
  allow-credentials: false

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false

# Get your keys at: https://www.google.com/recaptcha/admin
google:
  recaptcha:
    secret: "6LdkwTIsAAAAABTv_wOO74vbabBi018aMIjEBb0H"
    verify-url: https://www.google.com/recaptcha/api/siteverify

banxico:
  api-url: "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos/oportuno?token="
  token: "50275914e8b7ee04be8807d102f076c52bebb855410664f31a54e7bca0c3de38"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
