server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: travelandrepeat-be
  mail:
    host: ${MAIL_HOST}
    port: 587
    # see https://myaccount.google.com/u/1/apppasswords
    username: ${MAIL_QUOTATION_FROM}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}
          connectiontimeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

# Agent Mail
mail:
  agent-to: ${MAIL_AGENT_TO}
  quotation-from: ${MAIL_QUOTATION_FROM}

cors:
  allowed-origins-patterns: "*" # "http://localhost:3000"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: "*"
  allow-credentials: false

# Get your keys at: https://www.google.com/recaptcha/admin
google:
  recaptcha:
    secret: ${RECAPTCHA_SECRET}
    verify-url: https://www.google.com/recaptcha/api/siteverify

banxico:
  api-url: "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos/oportuno?token="
  token: ${BANXICO_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  expiration: "3600000" # 1 hour in milliseconds

# expose health and info endpoints over HTTP
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
